name: 'Flake8 Pull Request Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - '**.py'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.py'
      - name: Install flake8
        run: pip install flake8
      - name: Run Flake8
        id: run-flake8
        if: always()
        run: |
          flake8 ${{ steps.changed-files.outputs.all_changed_files }} >> flake8.txt
      - name: Comment on PR
        if: always()
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          filePath: flake8.txt