name: 'Flake8 Pull Request Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: '**.py'
      - uses: usama2490/lintly-flake8-github-action@v1.1
        with:
          # The GitHub API token to create reviews with
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          args: "--config=.flake8 ${{ steps.changed-files.outputs.all_changed_files }}"