name: 'Pull Request Jira ID Commit Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Messages on PR
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(\[(TEST)-(\d+)\])'
          flags: 'gim'
          error: 'ERROR: One or more commit messages failed because no valid Jira IDs.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}