name: 'Push Level Jira ID Commit Check'
on: push

jobs:
  check-commit-message:
    name: Check Commit Message on Push
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(\[(TEST)-(\d+)\])'
          flags: 'gim'
          error: 'WARNING: Commit message is missing Jira items. PRs will fail on status check.'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}