on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

name: Check For Jira Key on Push

jobs:
  Check_Commit:
    runs-on: ubuntu-latest
    name: Commit Checker
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find in commit messages
      id: find_issue_keys
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: commits

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0
    
    - name: Check for key
      run: |
        if [[ -n "${{ steps.find_issue_keys.outputs.issue }}" ]]; then
          echo "Jira issue keys were found. Proceeding with the push."
        else
          echo "No Jira issue keys were found. Skipping the push."
          pwd
          ls
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git reset --hard HEAD~1
          git pull
          git push
          exit 1  # Exit the workflow with an error status
        fi