on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened  # This triggers the workflow when a new PR is created
      - synchronize  # This triggers the workflow when an existing PR is updated

name: Check For Jira Key on Push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Commit Checker
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: commits